set -g mouse on
set -g history-limit 10000
set -g default-terminal "tmux-256color"
set -g status-interval 5
set -g status-left " #[bold]#S "
set -g status-right " %Y-%m-%d %H:%M "

bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux config reloaded"
bind c new-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"